version: 0.2

phases:
  pre_build:
    commands:
      - echo "-----------------"
      - git submodule init
      - git submodule update --recursive
      - echo "================="
  build:
    commands:
      - echo "-----------------"
      - hugo -v
      - ls -alh
      - echo "================="
artifacts:
  files:
    - "**/*"
  base-directory: public