version: 0.2

phases:
  pre_build:
    commands:
      - echo "In pre_build phase.."
      - echo "Current directory is $CODEBUILD_SRC_DIR"
  build:
    commands:
      - echo "-----------------"
      - hugo -v
      - ls -alh
artifacts:
  files:
    - "**/*"
  base-directory: public