# 缺少 git 解決不了 submodule 問題...
# 如果找到 git binary for `klakegg/hugo:ci:ui` 應該有解
version: 0.2

phases:
  pre_build:
    commands:
      - echo "-----------------"
      - git submodule init
      - git submodule update --recursive
      - echo "================="
  build:
    commands:
      - echo "-----------------"
      - hugo -v
      - ls -alh
      - echo "================="
artifacts:
  files:
    - "**/*"
  base-directory: public