version: 0.2

phases:
  build:
    commands:
      - echo "-----------------"
      - hugo -v
      - ls -alh
      - echo "================="
artifacts:
  files:
    - "**/*"
  base-directory: public