version: 0.2

phases:
  install: 
    runtime-versions:
      python: 3.9
    commands:
      - echo "------ Installing hugo ------"
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_0.110.0_linux-amd64.deb
      - dpkg -i hugo.deb
      - echo "============================="
  pre_build:
    commands:
      - echo "-----------------"
      - git submodule init
      - git submodule update --recursive
      - echo "================="
  build:
    commands:
      - echo "-----------------"
      - hugo -v
      - ls -alh
      - echo "================="
artifacts:
  files:
    - "**/*"
  base-directory: public